### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by cheesemarathon** [lamarios/Homedash2#2]
Hey
Just found this from your plug on reddit! First of all, it looks awesome. However I tend to run as many of my services as I can via docker for easy of deployment. Any chance you would be interested in creating a docker image? If not, I can have a crack at creating a dockerfile!

Thanks for creating this!

**Comment by lamarios** [comment]
Depending on the  complexity of the docker image you're expecting I might already have that somewhere as i used to run it in docker but changed my mind later.

If you want something where you can control the UID/GID who's running the container then you can chime in.

But before that I'll need to make some changes on the project over the week end because now it only works with Oracle JRE and i want it to run openJDK but now it doesn't work.

**Comment by cheesemarathon** [comment]
Would you mind sending me what dockerfiles you have, if you can find them :stuck_out_tongue_closed_eyes: 

Then I can use that as a bit of a starting point and see if there are any changes we might need to make. I noticed that you have been making the changes for use with openJDK

**Comment by lamarios** [comment]
You can find a beginning of implementation here: 

https://github.com/lamarios/Homedash2/tree/master/web/docker

but it's not working very well, somehow the CSS doesn't apply and the plugins are not found when trying to add a new one. 

I did two things this week end, making the app in a fat jar and creating the docker image using that fat jar. I'm not sure which one is not working properly (i'd guess the fat jar). If you want to get a go at it, you can try to create an image using the released that already exist (non fat jar version).

The changes for openJDK worked but then it stopped working with Oracle JRE.. which is the one i use on my server so i reverted them, I didn't get the time to find a proper solution; I need to investigate more...

**Comment by lamarios** [comment]
Ok, I've fixed the issues with the different JRE and stuff, we can focus on the docker image :) 

I'll have a look over the week end. If you happen to have time before that, even better.

**Comment by lamarios** [comment]
I've setup the whole docker thingy, You can have a look at the README on the repo main page.

Last remaining task is to allow UID and GID environment variables to run the container under a different user but it's more than usable. 

I'll close the issue first. Raise any new one if you have any difficulty.

**Comment by lamarios** [comment]
Alright, all done and documentation updated.

**Comment by cheesemarathon** [comment]
Thanks so much for this. Sorry I'm only just replying and wasn't much help! I've been on holiday for the past few days. I'll be sure to spin this up ASAP and let you know how I get on! Thanks again :smile: :+1:

**Comment by lamarios** [comment]
No problem. It also pushed me to clear few things up and make some other simpler.
The image is big though, I need to see if the slimmer images from openjdk would work too.
