### ISSUE TITLE
How do I get this working?

### ISSUE THREAD

**Issue by jacobhweeks** [lamarios/Homedash2#28]
I have started an instance of Ubuntu 20.04 server and installed maven and openjdk 11, but when I attempt to use maven to install, I get an error and cannot complete. Could someone please include a tutorial on how to get this up and running?

**Comment by lamarios** [comment]
You can download from the releases here: https://github.com/lamarios/Homedash2/releases

Then follow the "run from distribution" in the README.

**Comment by lamarios** [comment]
Download the homedash-version.jar file.

**Comment by jacobhweeks** [comment]
Okay, thanks.
