### ISSUE TITLE
Can't refresh module:MediaCover37posterjpg.jpg (Permission denied)

### ISSUE THREAD

**Issue by cheesemarathon** [lamarios/Homedash2#3]
I get the following error with the Radarr module when loading HomeDash
```
Can't refresh module:MediaCover37posterjpg.jpg (Permission denied)
```
Any ideas on how to fix this?

**Comment by cheesemarathon** [comment]
Similar issue seems to exist with Sonarr

**Comment by lamarios** [comment]
Are you running the container as root or with a specified user is and group is.

**Comment by cheesemarathon** [comment]
Sorry, I lied! I'm running it with the UID 99 and the GID 100. This is the same UID and GID im running Sonarr and Radarr with.

**Comment by lamarios** [comment]
Could you share with me the docker command you're using ?

**Comment by cheesemarathon** [comment]
HomeDash:
```
docker create --name='Homedash_Test' --net='host' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'SALT'='etCZ8D32hWl3ySRU' -e 'TCP_PORT_4657'='4657' -e 'GID'='100' -e 'UID'='99' -v '/mnt/user/appdata/homedash':'/data':'rw' 'gonzague/homedash'
```
Radarr:
```
docker create --name='radarr' --net='bridge' -e TZ="Europe/London" -e HOST_OS="Unraid" -e 'PUID'='99' -e 'PGID'='100' -p '7878:7878/tcp' -v '/mnt/user/Download':'/data':'rw' -v '/mnt/user/Media/Movies/':'/movies':'rw' -v '/mnt/user/appdata/radarr':'/config':'rw' --memory=1G 'linuxserver/radarr'
```

**Comment by lamarios** [comment]
I can't figure out how to reproduce the issue.

Can you run this once the container is running: 
```
docker exec -it Homedash_Test bash
cd /app/cache
touch test
```

Does it work ?

**Comment by cheesemarathon** [comment]
There is no cache folder. The only thing in the app folder are two files:
```
homedash.jar  homedash.properties
```

**Comment by lamarios** [comment]
can you give me the output of in the /app folder
```
ls -l
```

and try to run the command i gave you earlier in that /app folder.

**Comment by cheesemarathon** [comment]
`ls -l` in the app folder returns:
```
-rw-r--r-- 1 root root 36692605 Sep  9 05:46 homedash.jar
-rw-r--r-- 1 root root       94 Sep 12 09:56 homedash.properties
```
The test command works:
```
$ echo "hello" > test
$ cat test
hello
```

**Comment by lamarios** [comment]
Interesting, it seems like the UID and GID variable are not being used.

On my machine i'm getting:
```
drwxr-xr-x 7 abc abc     4096 Sep 12 17:13 cache
-rw-r--r-- 1 abc abc 36692605 Sep  9 12:46 homedash.jar
-rw-r--r-- 1 abc abc     1131 Sep 12 17:12 homedash.properties
drwxr-xr-x 2 abc abc     4096 Sep 12 17:12 logs
```

and yours is root while it shouldn't, If you run
```
echo $GID
echo $UID
```

Do you get back what is set in your docker create command ?

**Comment by lamarios** [comment]
Additionally, can you give me the output of:
```
docker exec -it Homedash_Test bash
ps axu  | grep homedash
```

while the container is running

**Comment by cheesemarathon** [comment]
```
$ ps axu | grep homedash
sh: 1: ps: not found
```

**Comment by lamarios** [comment]
Hmm that’s strange. Is the image up to date ?

**Comment by cheesemarathon** [comment]
Yes, i just removed the container, deleted the image and pulled `gonzague/homedash:latest` to re-create the container

**Comment by cheesemarathon** [comment]
Ah, that seems to have fixed the `ps` issue. Here is the output:
```
$ ps axu  | grep homedash
root        21  0.0  0.0  28540  3124 ?        S    11:29   0:00 runuser -l abc -c java  -Dconfig.file=/app/homedash.properties -jar homedash.jar
abc         22  0.0  0.0   2368   808 ?        Ss   11:29   0:00 -sh -c java  -Dconfig.file=/app/homedash.properties -jar homedash.jar
abc         25  2.3  2.4 7844480 392512 ?      Sl   11:29   0:46 java -Dconfig.file=/app/homedash.properties -jar homedash.jar
root       337  0.0  0.0   6872   928 pts/0    S+   12:02   0:00 grep homedash
```

**Comment by cheesemarathon** [comment]
The original error does still exist however.

**Comment by lamarios** [comment]
Can you rerun the previous command on the container now that you have the new version ?
```
ls -l /app
echo $GID
echo $UID
```

**Comment by cheesemarathon** [comment]
Output from above commands:
```
$ ls -l app
total 35840
-rw-r--r-- 1 root root 36692605 Sep  9 05:46 homedash.jar
-rw-r--r-- 1 root root       94 Sep 12 11:29 homedash.properties
$ echo $GID
100
$ echo $UID
99
```

**Comment by lamarios** [comment]
Ok, i'm starting to get around this issue, it seems like in the GID you're using already exists in the base image i'm using that's why the ls -l shows all under root and you get permission denied the only difference is that the image doesn't even run for me with those group ids.

So there are two solutions:
1)  you use a different group id if possible
2) i need to fix the script to detect if a user id or group id already exists and use it instead of creating a "fake" abc:abc user/group and runing the program using it.
For the second one you'll have to wait a little :)

**Comment by cheesemarathon** [comment]
Ok, no problem. I'll have to wait a little then. I'm running this on UnRAID and all files are owned by 99:100, so changing that along with all my other docker containers would be a huge pain. Thanks for your help so far!

**Comment by cheesemarathon** [comment]
Fixed it! Thanks!

**Comment by lamarios** [comment]
Great !
