### ISSUE TITLE
UniFi App Typo

### ISSUE THREAD

**Issue by cheesemarathon** [lamarios/Homedash2#4]
When in the menu to add a new app there is a typo for the UniFi app in the description. It currently says:
```
Gets a Unifi site current thourghput
```
When it should say:
```
Gets a Unifi site current throughput
```
thourghput should be throughput

**Comment by lamarios** [comment]
Alright. Will fix that. Thanks ! 

There are probably a ton more...

**Comment by cheesemarathon** [comment]
No problem!
