### ISSUE TITLE
Getting Started [Docker]

### ISSUE THREAD

**Issue by Brancliff** [lamarios/Homedash2#68]
Hey! I'm having trouble getting started with Homedash. I made my own docker-compose based on the CLI in the readme.

version: '3'
services:
  homedash:
    image: gonzague/homedash
    environment:
      - SALT=somerandomstring
    ports:
      - 3012:4567
    volumes:
      - "/share/CE_CACHEDEV1_DATA/Library/Projects/Homedash/Data:/data"
      - "/share/CE_CACHEDEV1_DATA/Library/Projects/Homedash/Localtime:/etc/localtime:ro"

When trying to create the container, this error pops up instead:

Deployment error
failed to deploy a stack: Creating homedashtest_homedash_1 ... [1A[2K Creating homedashtest_homedash_1 ... [31merror[0m [1B ERROR: for homedashtest_homedash_1 Cannot start service homedash: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/share/CE_CACHEDEV1_DATA/Library/Projects/Homedash/Localtime" to rootfs at "/etc/localtime" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type ERROR: for homedash Cannot start service homedash: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/share/CE_CACHEDEV1_DATA/Library/Projects/Homedash/Localtime" to rootfs at "/etc/localtime" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type Encountered errors while bringing up the project. : exit status 1

I'm running all of this through Docker on a QNAP NAS, TS-451+ (though I don't know if that would affect anything).

**Comment by lamarios** [comment]
Usually /etc/localtime is a file that points to /usr/share/zoneinfo/Europe/Paris for example based on your current time. It looks like the container is complaining that /share/CE_CACHEDEV1_DATA/Library/Projects/Homedash/Localtime is a directory and not a file. You should be able to run the container without mounting this volume it will work just fine but its time zone is going to be UTC.

**Comment by Brancliff** [comment]
Thank you for the quick response! I was able to set up the container by axing that line and defining the time zone in the environmental variables.

I'm setting up my homedash but still having some other issues. Selecting a google calendar module seems to break the system - All modules will disappear and Homedash will not display the form factor (desktop, tablet, etc) in the top-right. Attached are some logs from container's terminal when I tried to do this. Deleting homedash.mv.db and restarting the container will allow me to start fresh.

[_homedash_logs.txt](https://github.com/lamarios/Homedash2/files/9451506/_homedash_logs.txt)

**Comment by lamarios** [comment]
It's been a very long while I haven't used the google calendar plugin myself. Some library I was using might have become outdated.

This project is currently almost abandoned and I unfortunately don't have much bandwidth to look into it.  If you still want to use it I suggest you to stop the container, delete the files in your Data directory and start from scratch without this particular module.
