### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by rastaman** [lamarios/Homedash2#71]
Hi @lamarios , i play with your project and updated it somewhat on my fork and was wondering if you could put a license for it so i can properly maintain it?

Thanks for your time and have a nice week-end, best regards!

**Comment by lamarios** [comment]
I added a license, I chose the most permissive one. Curious to see what you will come with :)  Good luck, the code is quite messy !

**Comment by rastaman** [comment]
Thanks a lot! yes, that is not so messy but a little bit exotic ;-), that is for toying with upgrading java project and i like the look you have give to it. Thanks again, bye!
